# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: alpine:3.11
    parallelism: 3
    resource_class: small
    environment:
      OPA_VERSION: 1.18
    working_directory: ~/opa-mutator-app
    steps:
      - run: ls -R .
      - run: apk add --update make jq
      - run: wget https://github.com/open-policy-agent/opa/releases/download/v0.18.0/opa_linux_amd64 -O /usr/local/bin/opa
      - run: make -s run_tests
      - run: make -s run_coverage