version: 2.1

orbs:
  architect: giantswarm/architect@0.8.13

workflows:
  build:
    jobs:
      - architect/go-build:
          name: build-opa-mutator-app
          binary: opa-mutator-app
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-opa-mutator-app-to-docker
          image: "quay.io/giantswarm/opa-mutator-app"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build-opa-mutator-app
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-opa-mutator-app-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "opa-mutator-app"
          requires:
            - push-opa-mutator-app-to-docker
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-opa-mutator-app-to-aws-app-collection
          app_name: "opa-mutator-app"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-opa-mutator-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
