apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "opa.fullname" . }}-psp
  labels:
{{ include "opa.labels.standard" . | indent 4 }}
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: RunAsAny
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - secret
    - configMap
    - hostPath
    - emptyDir
  allowPrivilegeEscalation: false
